//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fotomaya.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_Foto
    {
        public int foto_id { get; set; }
        public string foto_uzanti { get; set; }
        public Nullable<int> admin_id { get; set; }
    
        public virtual Admin Admin { get; set; }
    }
}
