//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fotomaya.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Admin()
        {
            this.A_Foto = new HashSet<A_Foto>();
        }
    
        public int admin_id { get; set; }
        public string admin_kullaniciadi { get; set; }
        public string admin_sifre { get; set; }
        public string admin_sifre_tekrar { get; set; }
        public string admin_ad { get; set; }
        public string admin_soyad { get; set; }
        public string admin_telefon { get; set; }
        public string admin_email { get; set; }
        public string admin_adres { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<A_Foto> A_Foto { get; set; }
    }
}
