//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fotomaya.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ayar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ayar()
        {
            this.Fotograf = new HashSet<Fotograf>();
        }
    
        public int ayar_id { get; set; }
        public string site_ad { get; set; }
        public string site_baslik { get; set; }
        public string site_hakkimizda { get; set; }
        public string site_iletisim_telefon { get; set; }
        public string site_iletisim_email { get; set; }
        public string site_iletisim_adres { get; set; }
        public string site_arkaplan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fotograf> Fotograf { get; set; }
    }
}
