//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fotomaya.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fotograf
    {
        public int foto_id { get; set; }
        public string foto_uzanti { get; set; }
        public Nullable<System.DateTime> foto_yuklenme_tarih { get; set; }
        public Nullable<int> kullanici_id { get; set; }
        public Nullable<int> kategori_id { get; set; }
        public int foto_durum_id { get; set; }
        public Nullable<int> ayar_id { get; set; }
    
        public virtual FotoDurum FotoDurum { get; set; }
        public virtual Fotograf_Kategori Fotograf_Kategori { get; set; }
        public virtual Kullanici Kullanici { get; set; }
        public virtual Ayar Ayar { get; set; }
    }
}
