//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fotomaya.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hakkimizda
    {
        public int hakkimizda_id { get; set; }
        public string hakkimizda_baslik { get; set; }
        public string hakkimizda_aciklama { get; set; }
    }
}
