//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fotomaya.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hizmet
    {
        public int hizmet_id { get; set; }
        public string hizmet_baslik { get; set; }
        public string hizmet_aciklama { get; set; }
        public string hizmet_gorsel { get; set; }
    }
}
