//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fotomaya.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanici
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kullanici()
        {
            this.Fotograf = new HashSet<Fotograf>();
            this.K_Foto = new HashSet<K_Foto>();
        }
    
        public int kullanici_id { get; set; }
        public string kullanici_email { get; set; }
        public string kullanici_sifre { get; set; }
        public string kullanici_sifre_tekrar { get; set; }
        public string kullanici_ad { get; set; }
        public string kullanici_soyad { get; set; }
        public string kullanici_telefon { get; set; }
        public string kullanici_adres { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fotograf> Fotograf { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<K_Foto> K_Foto { get; set; }
    }
}
